### ISSUE TITLE
Are you looking for help?

### ISSUE THREAD

**Issue by avivbiton** [shashankgupta06/Pokemon-Game#1]
Do you need help on this one? I'd be happy to help on my free time, if so, is there anything specific you need help with?

**Comment by itsfalcon0717** [comment]
Well my goal is to complete a whole pokemon game as i am striving to get into professional game development. I am still new to game development and therefore it takes me a lot of time to fix issues and add progress. If you have played Pokemon before, you probably know the work this project is missing. 

In specific, some major issues you could help with are:
- i am unable to fix the buggy player collision 
- you could complete the interiors to the other pallet town buildings?

Most of my updated code is in the collider2 branch and once the player collision is fixed, we can merge all of that to master. Other than that, you can add whatever features you see fit as i previously mentioned that i am new and it could take me forever to complete this project. 

Any help would be greatly appreciated thank-you!

**Comment by jeepitou** [comment]
Hey I would also like to help, saw your post on reddit.  Could we maybe open a slack or discord?

**Comment by itsfalcon0717** [comment]
yes! whats your discord handle?

**Comment by jeepitou** [comment]
Jeepitou#0004
